from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    CustomTokenObtainPairView,
    logout_view,
    UserViewSet,
    UserPermissionsView,
    ActivityLogListView,
)

router = DefaultRouter()
router.register(r'users', UserViewSet, basename='user')

urlpatterns = [
    # Auth
    path('login/',   CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('refresh/', TokenRefreshView.as_view(),          name='token_refresh'),
    path('logout/',  logout_view,                         name='logout'),

    # Users CRUD (generated by router: /users/ and /users/<pk>/)
    path('', include(router.urls)),

    # Per-user permissions
    path('users/<int:id>/permissions/', UserPermissionsView.as_view(), name='user-permissions'),

    # Activity logs
    path('logs/', ActivityLogListView.as_view(), name='activity-logs'),
]
