# Generated by Django 5.1 on 2026-04-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '__first__'),
        ('teachers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('lang', models.CharField(default='ar', max_length=10)),
                ('created_by_user_id', models.IntegerField(blank=True, db_column='iduser', null=True)),
            ],
            options={
                'db_table': 'range',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DistributionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_label', models.CharField(db_column='numroom', max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(db_column='tech_name', max_length=255)),
                ('degree', models.CharField(blank=True, default='', max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('type', models.PositiveSmallIntegerField(default=1)),
                ('classroom', models.ForeignKey(blank=True, db_column='idroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_assignments', to='classrooms.classroom')),
                ('teacher', models.ForeignKey(blank=True, db_column='tech_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_assignments', to='teachers.teacher')),
                ('batch', models.ForeignKey(db_column='idrange', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='distributions.distributionbatch')),
            ],
            options={
                'db_table': 'tech_divide',
                'ordering': ['-id'],
            },
        ),
    ]
