# Generated by Django 5.2.12 on 2026-04-05 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('lang', models.CharField(default='ar', max_length=10)),
                ('created_by_user_id', models.IntegerField(blank=True, db_column='iduser', null=True)),
                ('classroom', models.ForeignKey(blank=True, db_column='idroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='classrooms.classroom')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-id'],
            },
        ),
    ]
