# Generated by Django 5.2.12 on 2026-04-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(choices=[('استاذ', 'استاذ'), ('استاذ مساعد', 'استاذ مساعد'), ('مدرس', 'مدرس'), ('مدرس مساعد', 'مدرس مساعد')], max_length=100)),
                ('degree', models.CharField(choices=[('دكتوراه', 'دكتوراه'), ('ماجستير', 'ماجستير'), ('بكالوريوس', 'بكالوريوس')], max_length=100)),
                ('type', models.PositiveSmallIntegerField(default=1)),
                ('lang', models.CharField(default='ar', max_length=10)),
                ('created_by_user_id', models.IntegerField(blank=True, db_column='iduser', null=True)),
            ],
            options={
                'db_table': 'teaching_management',
                'ordering': ['name'],
            },
        ),
    ]
