# Generated by Django 5.1 on 2026-04-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacherexclusion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_excluded',
            field=models.BooleanField(default=False, verbose_name='مستثنى دائماً'),
        ),
    ]
