# Generated by Django 5.1 on 2026-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_add_is_excluded_to_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='exclusion_reason',
            field=models.TextField(blank=True, default='', verbose_name='سبب الاستثناء'),
        ),
    ]
