# Generated by Django 5.2.12 on 2026-04-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(db_column='roomnumber', max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('num_invigilators', models.PositiveIntegerField(db_column='numlnvigilators')),
                ('lang', models.CharField(default='ar', max_length=10)),
                ('created_by_user_id', models.IntegerField(blank=True, db_column='iduser', null=True)),
            ],
            options={
                'db_table': 'classroom',
                'ordering': ['room_number'],
            },
        ),
    ]
