# Generated by Django 5.1 on 2026-04-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='مكان القاعة'),
        ),
    ]
